# Generated by Django 2.0 on 2018-09-14 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180913_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '< Commentaire >'},
        ),
    ]
