# Generated by Django 2.0 on 2018-09-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_nbr_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '< Article >', 'verbose_name_plural': '< Articles >'},
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name': '< Categorie >', 'verbose_name_plural': '< Categories >'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '< Commentaire >', 'verbose_name_plural': '< Commentaires >'},
        ),
    ]
